#!/usr/bin/env python3
# -*- coding: utf-8 -*-

#if-elif-else 分支语言

height=1.75
weight=80.5
bmi=weight/(height**2)
if bmi <18.5:
    result='过轻'
elif bmi<25:
    result='正常'
elif bmi<28:
    result='过重'
elif bmi<32:
    result='肥胖'
elif bmi>=32:
    result='严重肥胖'
else:
    pass
print(result)


# for,while,break,continue

#列表循环
list_var=['a','b','c']
for i in list_var:
    print(i)

#字典循环
dict_var={'a':1,'b':2,'c':3}
for i in dict_var:
    print(i)   #输出key
    print(dict_var[i]) #输出值
    print('-------------------')
    
# 1-100求和    
sum_=0    
for i in range(1,101):
    sum_+=i
print(sum_)

i=0
sum_=0
while i<101:
    sum_+=i
    i=i+1
print(sum_)   

i=0
sum_=0
while True:
    sum_+=i
    i=i+1
    if i >100:
        break
print(sum_)


i=0
sum_=0
for i in range(1,101):
    if i%2==0:
        continue
    sum_+=i
print(sum_)    
